### ISSUE TITLE
update needed for instructions on exporting existing wordle stats

### ISSUE THREAD

**Issue by 916253** [sneakers-the-rat/local_wordle#1]
since wordle has now been nyt rebranded and moved over to their site, the item to grab for outputting existing stats has changed from `statistics` to `nyt-wordle-statistics`. not doing a PR because I don't know whether you'd prefer to list both in case someone has been using a wordle clone or just swap it out, but figured i'd at least raise attention to it

**Comment by sneakers-the-rat** [comment]
got it, tysm ❤️❤️❤️
https://github.com/sneakers-the-rat/local_wordle/commit/f94a13bee2d9a408af4977f0f32e5f9679e639c7
